// Lesson content for the Learn section, organized by topic. Each lesson has a
// few content sections plus a short interactive quiz; LearnPage.jsx renders
// this data and useLessonProgress.js tracks which lessons a learner has
// passed (persisted to localStorage, mirroring the onboarding "seen" flag).

export const LEARN_TOPICS = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: 'rocket',
    lessons: [
      {
        id: 'what-is-paper-trading',
        title: 'What is paper trading?',
        summary: 'What this simulator does — and doesn\'t do — with your money.',
        sections: [
          {
            heading: 'The short version',
            body: "TradeScrim is a paper-trading simulator. That means every price you see is a real, market price (delayed by data provider rules), but every dollar you trade with is pretend. There's no bank account, brokerage, or card connected — the $10,000 you start with is virtual cash that only exists inside this app.",
          },
          {
            heading: 'Why practice with fake money?',
            body: "Real investing has real consequences: a bad trade can cost you rent money. Paper trading removes that risk so you can make mistakes, watch what happens, and build intuition for how markets move before any real money is on the line. Professional traders and finance students use this exact technique to test strategies.",
          },
          {
            heading: "What paper trading won't teach you",
            body: "Two things behave differently once real money is on the line: the emotional pressure of watching a real loss grow, and the cost of trading (fees, taxes, and the fact that large real orders can nudge the market price). Keep that in mind for later — the mechanics here are close, but the stakes and the psychology aren't.",
          },
        ],
        quiz: [
          {
            question: 'In TradeScrim, where do the stock prices come from?',
            options: [
              'Randomly generated by the app',
              'Real market data, just like a live brokerage app',
              'Prices set by other players',
              'Historical prices from 10 years ago',
            ],
            correctIndex: 1,
            explanation: 'Prices are pulled from real market data — only the money you trade with is fake.',
          },
          {
            question: 'What is the main advantage of paper trading before investing real money?',
            options: [
              "It guarantees you'll make money later",
              'It removes financial risk while you learn how markets behave',
              'It is required by law before opening a brokerage account',
              'It automatically picks good stocks for you',
            ],
            correctIndex: 1,
            explanation: 'Paper trading lets you practice decision-making without risking real money.',
          },
        ],
      },
      {
        id: 'how-this-simulator-works',
        title: 'How this simulator works',
        summary: 'Starting cash, the trading loop, and what gets tracked for you.',
        sections: [
          {
            heading: 'Your starting point',
            body: 'Every new account starts with $10,000 in virtual cash. That number is a constant across all accounts, which is what makes the Leaderboard a fair comparison — everyone starts from the same line.',
          },
          {
            heading: 'The trading loop',
            list: [
              'Search for a company or ticker symbol on the Dashboard.',
              'Review its current price and recent price chart.',
              'Place a simulated buy or sell market order.',
              'Watch your holdings, cash, and profit/loss update immediately.',
              'Check the Leaderboard to see how your return compares to other traders.',
            ],
          },
          {
            heading: 'Everything is tracked for you',
            body: "Every order you place is saved to your transaction history, and your holdings automatically combine into an average cost when you buy the same stock more than once. You never have to do the math by hand — this Learn section is here to help you understand what the numbers mean.",
          },
        ],
        quiz: [
          {
            question: 'How much virtual cash does every new account start with?',
            options: ['$1,000', '$5,000', '$10,000', '$100,000'],
            correctIndex: 2,
            explanation: 'Every account starts with $10,000 in virtual cash — the same for everyone.',
          },
          {
            question: 'Why does every account start with the same amount of cash?',
            options: [
              "It's a technical limitation",
              'So the Leaderboard is a fair, apples-to-apples comparison',
              "It's the maximum allowed",
              'It has no particular reason',
            ],
            correctIndex: 1,
            explanation: 'A shared starting point means leaderboard rankings reflect trading decisions, not who started with more money.',
          },
        ],
      },
    ],
  },
  {
    id: 'reading-the-market',
    title: 'Reading the Market',
    icon: 'trending-up',
    lessons: [
      {
        id: 'ticker-symbols-quotes',
        title: 'Ticker symbols & quotes',
        summary: 'How to read a stock symbol, price, and market state.',
        sections: [
          {
            heading: 'What a ticker symbol is',
            body: "A ticker symbol is the short code that identifies a company on a stock exchange — AAPL for Apple, TSLA for Tesla, MSFT for Microsoft. You'll use these symbols to search for and trade a company in the app.",
          },
          {
            heading: 'Reading a quote',
            body: 'When you look up a stock you\'ll see its current price, the dollar and percent change from the previous close, and a market state (PRE, REGULAR, POST, or CLOSED). The change tells the story of the day so far — a stock at $150, up $3 (+2%), has gained ground since the market opened.',
          },
          {
            heading: 'Market state matters',
            body: "Markets aren't open 24/7. REGULAR means the main trading session is live. PRE and POST are the shorter, less liquid windows before and after it. CLOSED means the price you're seeing is simply the last available price — it won't move until trading resumes.",
          },
        ],
        quiz: [
          {
            question: 'What does the ticker symbol AAPL represent?',
            options: ['A stock exchange', 'Apple Inc.', 'An order type', 'A type of mutual fund'],
            correctIndex: 1,
            explanation: "AAPL is Apple Inc.'s ticker symbol on the NASDAQ exchange.",
          },
          {
            question: 'If a quote shows a market state of CLOSED, what does that mean?',
            options: [
              'The company went bankrupt',
              "You can't ever buy that stock again",
              "The price shown is the last traded price and won't move until the market reopens",
              'The price is fake',
            ],
            correctIndex: 2,
            explanation: "CLOSED just means the exchange isn't currently trading that symbol — the price is frozen at its last trade.",
          },
        ],
      },
      {
        id: 'reading-a-price-chart',
        title: 'Reading a price chart',
        summary: 'What the axes mean, and why timeframe changes the story.',
        sections: [
          {
            heading: 'What the chart shows',
            body: "The price chart plots a stock's closing price over time. The horizontal axis is time, the vertical axis is price — an upward-sloping line means the price has been rising over that period, a downward slope means it's been falling.",
          },
          {
            heading: 'Choosing a timeframe',
            body: "Switching between 1D, 1W, 1M, and longer ranges changes the story the chart tells. A stock can be down for the day but up for the year — neither view is \"wrong\", they just answer different questions. Zooming out generally smooths over daily noise and shows the longer trend.",
          },
          {
            heading: 'A chart is not a prediction',
            body: "It's tempting to draw a line through the recent past and extend it into the future — but a price chart only shows what already happened. It's useful for spotting trends and volatility, not for guaranteeing what comes next.",
          },
        ],
        quiz: [
          {
            question: 'On a price chart, what does the vertical axis usually represent?',
            options: ['Time', 'Trading volume', 'Price', 'Number of investors'],
            correctIndex: 2,
            explanation: 'The vertical axis plots price; the horizontal axis plots time.',
          },
          {
            question: "Why might a stock look 'down' on a 1-day chart but 'up' on a 1-year chart?",
            options: [
              "That's impossible — charts always agree",
              'Different timeframes cover different periods and can tell different stories',
              'The 1-year chart is always wrong',
              'Prices reset every year',
            ],
            correctIndex: 1,
            explanation: 'Short-term dips are common even inside a longer uptrend (and vice versa) — timeframe changes the story.',
          },
        ],
      },
      {
        id: 'chart-types',
        title: 'Chart types: line, candlestick, and volume',
        summary: 'What each style of chart shows that the others don\'t.',
        sections: [
          {
            heading: 'Line charts: the simple trend',
            body: "The line chart used elsewhere in this app connects each period's closing price into a single line. It's the easiest to read at a glance — good for spotting the overall trend — but it throws away everything that happened between opens and closes, like how far the price swung during the day.",
          },
          {
            heading: 'Candlestick charts: a full period in one shape',
            body: "A candlestick packs four prices into one shape for a single period (a day, an hour, whatever the timeframe is): the open, close, high, and low. The thick part (the \"body\") spans open to close — traditionally green/white if the close was higher than the open, red/black if lower. The thin lines above and below (the \"wicks\" or \"shadows\") mark the highest and lowest prices reached during that period, even if the price didn't finish there. A long wick means the price was pushed hard in that direction and then reversed before the period ended.",
          },
          {
            heading: 'Volume charts: how much conviction was behind the move',
            body: "Volume bars, usually shown beneath the price, count how many shares traded during each period. Price tells you what happened; volume tells you how much participation was behind it. A big price move on heavy volume suggests broad agreement and is more likely to hold. The same move on thin volume — few shares changing hands — is easier to reverse.",
          },
        ],
        quiz: [
          {
            question: 'On a candlestick, what do the thin "wick" lines above and below the body show?',
            options: [
              'The opening and closing prices',
              'The highest and lowest prices reached during that period',
              'The trading volume',
              'The average price over the period',
            ],
            correctIndex: 1,
            explanation: 'The body spans open-to-close; the wicks mark the high and low the price touched during the period, even briefly.',
          },
          {
            question: 'A big price move on unusually heavy trading volume usually suggests what?',
            options: [
              'The move is fake and will definitely reverse',
              'Broad participation and conviction behind the move, making it more likely to hold',
              'The stock has been delisted',
              'Volume has no relationship to price moves',
            ],
            correctIndex: 1,
            explanation: 'Heavy volume behind a move means a lot of traders agreed with the direction, which tends to make the move more durable than the same move on thin volume.',
          },
        ],
      },
    ],
  },
  {
    id: 'placing-orders',
    title: 'Placing Orders',
    icon: 'receipt',
    lessons: [
      {
        id: 'market-orders',
        title: 'Market orders',
        summary: 'What a market order does, and the trade-off it makes.',
        sections: [
          {
            heading: 'What a market order does',
            body: 'A market order tells the system: buy (or sell) this stock right now, at whatever the current price is. It\'s the simplest order type, and it\'s what every trade in this simulator uses.',
          },
          {
            heading: 'The trade-off',
            body: "Speed and certainty of execution come at a small cost: you don't get to name your price. In fast-moving real markets, the price you see and the price you actually pay can differ slightly by the time your order reaches the exchange. That's the gap limit and stop orders exist to close — covered in the next topic.",
          },
          {
            heading: 'Before you click Buy',
            body: "Since a market order executes immediately, double-check the share count and estimated cost shown in the trade panel before confirming — there's no undo button once an order is placed, just like in a real brokerage.",
          },
        ],
        quiz: [
          {
            question: 'What does a market order guarantee?',
            options: ['A specific price', 'Immediate execution at the current price', 'A profit', "That the price won't change"],
            correctIndex: 1,
            explanation: 'A market order prioritizes speed of execution over price control — it fills right away at the going price.',
          },
          {
            question: 'Why might the price you actually pay differ slightly from the price you saw right before placing a market order?',
            options: [
              'It never differs',
              'Prices can move in the moment between when you see a quote and when the order reaches the exchange',
              'The app rounds all prices to the nearest dollar',
              'Market orders always fill at yesterday\'s closing price',
            ],
            correctIndex: 1,
            explanation: 'A market order fills at whatever the current price is at execution — which can have moved slightly since you last looked.',
          },
        ],
      },
      {
        id: 'buying-selling-cost-basis',
        title: 'Buying, selling & cost basis',
        summary: 'How average cost basis works, and realized vs. unrealized P&L.',
        sections: [
          {
            heading: 'Average cost basis',
            body: 'If you buy the same stock more than once at different prices, your holding tracks a single average cost basis — the weighted average of everything you paid. Buy 5 shares at $100 and 5 more at $120, and your average cost becomes $110, even though no single purchase was at that price.',
          },
          {
            heading: 'Realized vs. unrealized',
            body: "Profit and loss on shares you still own is \"unrealized\" — it's paper gains or losses that move with the current price and could vanish before you sell. The moment you sell, that gain or loss is \"realized\" — locked in for good.",
          },
          {
            heading: 'Selling and your cost basis',
            body: 'When you sell part of a position, the app compares the sale price to your average cost basis to calculate realized profit or loss on just those shares. Your remaining shares keep the same average cost basis they had before.',
          },
        ],
        quiz: [
          {
            question: "You buy 10 shares at $50, then 10 more at $70. What's your average cost basis per share?",
            options: ['$50', '$60', '$70', '$120'],
            correctIndex: 1,
            explanation: '(10×$50 + 10×$70) ÷ 20 shares = $60 average cost.',
          },
          {
            question: "When does a gain or loss become 'realized'?",
            options: ['The moment the price changes', 'Only at the end of the year', 'When you actually sell the shares', 'As soon as you buy'],
            correctIndex: 2,
            explanation: "Unrealized P&L is just on paper; it becomes realized only once you sell.",
          },
        ],
      },
    ],
  },
  {
    id: 'order-types',
    title: 'Order Types',
    icon: 'sliders',
    lessons: [
      {
        id: 'limit-orders',
        title: 'Limit orders',
        summary: 'Naming your price, at the cost of a guaranteed fill.',
        sections: [
          {
            heading: 'What a limit order does',
            body: 'A limit order lets you name a price instead of accepting whatever the market offers right now. A buy limit only fills at your limit price or lower; a sell limit only fills at your limit price or higher. In exchange for that control, you give up the market order\'s guarantee of an immediate fill — a limit order can sit unfilled for minutes, days, or indefinitely if the price never reaches your number.',
          },
          {
            heading: 'Why use one',
            body: 'Limit orders are useful when you have a specific price in mind — "I\'ll buy this dip if it drops to $40" or "I\'ll sell once it recovers to $55" — and would rather wait than pay whatever the market happens to be asking right now. They\'re also the standard way to trade a stock that isn\'t moving much, where the difference between the current price and your target price is small but still worth capturing.',
          },
          {
            heading: 'In this simulator',
            body: 'A placed limit order shows up as "Pending" in your Open Orders list. A background check runs periodically against live prices — once your buy limit price or higher is reached (for a sell) or your limit price or lower is reached (for a buy), it fills automatically at that price, exactly like a market order would, and moves your cash and holdings accordingly.',
          },
        ],
        quiz: [
          {
            question: 'You place a BUY limit order at $45 on a stock currently trading at $50. When can it fill?',
            options: [
              'Immediately, at $50',
              'Only if the price drops to $45 or lower',
              'Only if the price rises to $45 or higher',
              'It can never fill',
            ],
            correctIndex: 1,
            explanation: 'A buy limit only fills at your limit price or better (lower) — it waits for the price to come down to you.',
          },
          {
            question: 'What do you give up by using a limit order instead of a market order?',
            options: [
              'The ability to name your price',
              'The guarantee that it fills right away',
              'The ability to sell at all',
              'Nothing — limit orders are strictly better',
            ],
            correctIndex: 1,
            explanation: 'Limit orders trade the market order\'s "always fills now" guarantee for control over price.',
          },
        ],
      },
      {
        id: 'stop-orders',
        title: 'Stop orders',
        summary: 'A trigger price that turns into a market order once crossed.',
        sections: [
          {
            heading: 'What a stop order does',
            body: 'A stop order sits inactive until the price crosses a trigger you set — the "stop price" — at which point it becomes a market order and fills at whatever the price is right then. A sell stop set below the current price is the classic "stop-loss": if the price falls to your stop, the position sells automatically, capping further loss. A buy stop set above the current price is often used to catch a breakout: "if it breaks past $60, I want in."',
          },
          {
            heading: 'Stop orders are not price guarantees',
            body: 'This is the detail beginners most often miss: once triggered, a stop order fills at the market price, not at the stop price. In a fast-moving or gapping market, the price by the time it actually fills can be noticeably worse than your stop price — a real risk to understand, not just a technicality.',
          },
          {
            heading: 'In this simulator',
            body: 'A pending stop order is checked against live prices by the same background job as limit orders. The moment the trigger condition is met, it fills immediately at the price observed at that check — mirroring how a real stop order becomes a market order the instant it\'s triggered.',
          },
        ],
        quiz: [
          {
            question: 'You hold a stock at $80 and place a SELL stop at $70 to limit your downside. What happens once the price hits $70?',
            options: [
              'Nothing, it just watches',
              'It becomes a market order and sells at the current price',
              'It guarantees you sell at exactly $70',
              'It cancels automatically',
            ],
            correctIndex: 1,
            explanation: 'A triggered stop order fills at market — the price at that moment, which may not be exactly your stop price.',
          },
          {
            question: 'Why can a stop order fill at a worse price than the stop price you set?',
            options: [
              'It never can — the fill price always matches the stop price exactly',
              'Because once triggered it becomes a market order, and price can keep moving before it fills',
              'Because the simulator charges a fee',
              'Because stop orders only work on Fridays',
            ],
            correctIndex: 1,
            explanation: 'Triggering turns it into a market order — subject to whatever the price has moved to by the time it actually executes.',
          },
        ],
      },
      {
        id: 'stop-limit-orders',
        title: 'Stop-limit orders',
        summary: 'Combining a trigger price with a floor or ceiling on the fill.',
        sections: [
          {
            heading: 'Two prices, two jobs',
            body: 'A stop-limit order takes the trigger idea from a stop order and pairs it with the price control of a limit order. It has two prices: a stop price that arms the order, and a limit price that caps what you\'ll actually accept once armed. Nothing happens until the stop price is crossed — at that point, instead of becoming a market order, it becomes a limit order at your limit price.',
          },
          {
            heading: 'The trade-off versus a plain stop',
            body: 'This solves the plain stop order\'s "fills at any price" problem — a stop-limit sell will never execute below your limit price, no matter how far the market moves. The cost is the same one plain limit orders have: once armed, it might not fill at all if the price blows straight through your limit without pausing there. You\'re trading "guaranteed to get out" for "never get a price worse than I said."',
          },
          {
            heading: 'In this simulator',
            body: 'A stop-limit order shows as "Pending" until its stop price is crossed, at which point the background job marks it armed and starts checking it like a limit order — filling only once the price also satisfies the limit price.',
          },
        ],
        quiz: [
          {
            question: 'What does the stop price do in a stop-limit order?',
            options: [
              'It\'s the price the order fills at',
              'It arms the order, turning it into a limit order once crossed',
              'It cancels the order once reached',
              'It has no effect',
            ],
            correctIndex: 1,
            explanation: 'Crossing the stop price only arms the order — the limit price then controls whether and where it actually fills.',
          },
          {
            question: 'What is the main risk of a stop-limit order compared to a plain stop order?',
            options: [
              'It might fill at a much worse price than expected',
              'It might never fill at all, even after the stop triggers, if price moves past the limit',
              'It costs more to place',
              'It can only be used for selling',
            ],
            correctIndex: 1,
            explanation: 'Once armed, a stop-limit behaves like a limit order — it can sit unfilled if the price never comes back to your limit.',
          },
        ],
      },
    ],
  },
  {
    id: 'risk-and-diversification',
    title: 'Risk & Diversification',
    icon: 'scale',
    lessons: [
      {
        id: 'volatility',
        title: 'Volatility',
        summary: 'How much — and how fast — a price swings, and why that matters.',
        sections: [
          {
            heading: 'What volatility means',
            body: "Volatility describes how much — and how fast — a stock's price swings up and down. A low-volatility stock might move less than 1% on a typical day; a high-volatility stock can swing 5-10% or more.",
          },
          {
            heading: "Volatility isn't automatically bad",
            body: "Higher volatility means bigger potential gains and bigger potential losses in the same breath — it's a measure of uncertainty, not of quality. A steady, low-volatility company isn't necessarily a \"better\" investment than a volatile one; they just carry different risk profiles.",
          },
          {
            heading: 'Volatility and your emotions',
            body: 'The more volatile a holding, the more your portfolio value will jump around day to day. Watching a volatile stock swing 8% in an afternoon can tempt you into reacting emotionally instead of sticking to a plan.',
          },
        ],
        quiz: [
          {
            question: "What does 'high volatility' mean for a stock?",
            options: [
              'It always goes up',
              'Its price moves are frequent and large in both directions',
              'It is guaranteed to be a bad investment',
              'It has no trading volume',
            ],
            correctIndex: 1,
            explanation: 'Volatility measures the size and speed of price swings, in either direction.',
          },
          {
            question: 'Is high volatility always a bad sign?',
            options: [
              'Yes, avoid it entirely',
              'No — it just means bigger potential swings, both up and down',
              'Yes, it means the company is failing',
              'No, it means the stock will definitely rise',
            ],
            correctIndex: 1,
            explanation: "Volatility is about the size of price swings, not a verdict on whether they'll be good or bad.",
          },
        ],
      },
      {
        id: 'diversification',
        title: 'Diversification',
        summary: "Why spreading your bets protects the rest of your portfolio.",
        sections: [
          {
            heading: "Don't put all your eggs in one basket",
            body: "Diversification means spreading your money across multiple companies, sectors, or asset types so that one company's bad quarter — or a whole industry's downturn — doesn't sink your entire portfolio.",
          },
          {
            heading: 'What concentration risk looks like',
            body: "If your entire virtual portfolio is one stock and that company reports bad news, your whole account value can drop sharply in a single day. Spread across ten unrelated companies, the same bad news from one of them barely dents your total.",
          },
          {
            heading: 'Diversification in practice',
            body: 'You don\'t need dozens of positions to diversify meaningfully — even 5-10 holdings across different industries (tech, healthcare, energy, consumer goods) meaningfully reduces the damage any single company can do. Try building a small, varied portfolio here and compare how it behaves to a single big bet.',
          },
        ],
        quiz: [
          {
            question: 'What is the main benefit of diversification?',
            options: [
              'It guarantees higher returns',
              'It reduces the impact any single investment can have on your whole portfolio',
              'It eliminates all risk completely',
              'It lets you avoid doing research',
            ],
            correctIndex: 1,
            explanation: 'Diversification spreads risk around so no single holding can sink your entire portfolio.',
          },
          {
            question: 'Which portfolio is more diversified?',
            options: [
              '100% of your cash in one company',
              'Your cash split across 8 companies in different industries',
              'Your cash split between two companies in the same industry',
              'It doesn\'t matter',
            ],
            correctIndex: 1,
            explanation: 'Spreading across multiple companies and industries reduces concentration risk the most.',
          },
        ],
      },
    ],
  },
  {
    id: 'tracking-performance',
    title: 'Tracking Performance',
    icon: 'bar-chart',
    lessons: [
      {
        id: 'profit-and-loss',
        title: 'Profit & loss',
        summary: 'The difference between unrealized, realized, and total P&L.',
        sections: [
          {
            heading: 'Two kinds of P&L',
            body: "Your dashboard splits profit and loss into two numbers. Unrealized P&L is the paper gain or loss on shares you still hold, calculated against the current market price — it moves every time the price does. Realized P&L is money you've actually locked in by selling.",
          },
          {
            heading: 'Why the distinction matters',
            body: "A large unrealized gain can shrink — or vanish — if the price falls before you sell. Only realized gains are truly \"in the bank\". Watching both numbers separately helps you understand how much of your performance is confirmed versus still at the market's mercy.",
          },
          {
            heading: 'Total P&L',
            body: "Your total P&L combines both: realized gains or losses from past sales, plus the current unrealized gain or loss on everything you're still holding. It's the single best snapshot of how you're doing overall.",
          },
        ],
        quiz: [
          {
            question: 'Which type of P&L can still change value day to day?',
            options: ['Realized P&L', 'Unrealized P&L', 'Neither, both are fixed', 'Both change at the same fixed rate'],
            correctIndex: 1,
            explanation: 'Unrealized P&L tracks your current holdings against the live price, so it moves until you sell.',
          },
          {
            question: "When is a gain 'locked in'?",
            options: [
              'As soon as the price goes up',
              'Only once you sell the shares',
              'At the end of the trading day automatically',
              'Never — gains always disappear',
            ],
            correctIndex: 1,
            explanation: 'A gain becomes realized — locked in — only when you actually sell.',
          },
        ],
      },
      {
        id: 'roi-and-leaderboard',
        title: 'ROI and the Leaderboard',
        summary: 'How return percentage makes ranking traders fair.',
        sections: [
          {
            heading: 'What ROI measures',
            body: "Return on investment (ROI) expresses your profit or loss as a percentage of what you started with, rather than a raw dollar amount. A $500 gain means very different things to a $1,000 account and a $100,000 account — ROI puts everyone on the same scale.",
          },
          {
            heading: 'How the Leaderboard uses ROI',
            body: 'The Leaderboard ranks every trader by their ROI over a chosen time window — 1 day, 1 week, 1 month, 3 months, 6 months, 1 year, or all time — instead of raw portfolio value. Because everyone starts with the same $10,000, comparing ROI is a fair way to see whose recent decisions have performed best.',
          },
          {
            heading: 'Reading different time windows',
            body: 'A trader can rank #1 on the 1-day leaderboard after a lucky short-term swing, while ranking lower on the all-time board once that swing is measured against their whole history. Longer windows tend to reward consistent decision-making over lucky timing.',
          },
        ],
        quiz: [
          {
            question: 'Why does the Leaderboard rank by ROI percentage instead of total dollar value?',
            options: [
              'Dollar value is easier to calculate',
              'Because everyone starts with the same cash, ROI is a fairer comparison of trading performance',
              'ROI is always a bigger number',
              "It doesn't — it ranks by dollar value",
            ],
            correctIndex: 1,
            explanation: 'Since every account starts at the same $10,000, ranking by ROI% compares decisions, not starting capital.',
          },
          {
            question: 'What might explain a trader ranking #1 on the 1-day board but much lower on the all-time board?',
            options: [
              'A data error',
              "A short-term lucky swing that isn't representative of their longer track record",
              'The leaderboard is randomized',
              'All-time and 1-day always show the same order',
            ],
            correctIndex: 1,
            explanation: 'Short windows can be swayed by a single lucky (or unlucky) move; longer windows smooth that out.',
          },
        ],
      },
    ],
  },
  {
    id: 'investing-mindset',
    title: 'Investing Mindset',
    icon: 'brain',
    lessons: [
      {
        id: 'long-term-thinking',
        title: 'Long-term thinking',
        summary: 'Time in the market vs. timing the market.',
        sections: [
          {
            heading: 'Time in the market vs. timing the market',
            body: "Trying to buy right before a rally and sell right before a drop — \"timing the market\" — is notoriously difficult, even for professionals. A more reliable pattern historically has been simply staying invested over long periods, riding out the dips along the way.",
          },
          {
            heading: 'The cost of overtrading',
            body: "Frequent buying and selling doesn't just add real-world costs (fees, taxes) — it also multiplies the number of decisions you can get wrong. Each trade is a fresh bet on short-term direction, which is far harder to call correctly than long-term company performance.",
          },
          {
            heading: 'Using this simulator to practice patience',
            body: 'Because there\'s no real money at risk, it\'s easy to fall into rapid-fire trading just to see what happens. Try the opposite: pick a few companies you believe in, hold them, and check back over weeks instead of minutes. Compare how that feels — and performs — against more frequent trading.',
          },
        ],
        quiz: [
          {
            question: "What does 'time in the market vs. timing the market' refer to?",
            options: [
              'Trading only at night',
              'Staying invested over the long run instead of trying to predict short-term highs and lows',
              'Only trading when the market is closed',
              'Checking prices every minute',
            ],
            correctIndex: 1,
            explanation: 'It contrasts patient, long-term holding with attempts to precisely predict short-term price swings.',
          },
          {
            question: "What's one downside of frequent trading?",
            options: [
              'It guarantees losses',
              'Each trade is another short-term bet that can go wrong, and real trading adds costs like fees and taxes',
              'It is illegal',
              'It has no downsides',
            ],
            correctIndex: 1,
            explanation: 'More trades mean more chances to be wrong about short-term direction, plus real-world costs in a live account.',
          },
        ],
      },
      {
        id: 'common-beginner-mistakes',
        title: 'Common beginner mistakes',
        summary: 'Hype-chasing, concentration, and emotional decisions.',
        sections: [
          {
            heading: 'Chasing hype',
            body: "Buying a stock purely because it's trending or \"everyone's talking about it\" means buying after the price has often already risen a lot — and hype fades faster than it builds. Ask what you know about the company, not just what you've heard about the stock.",
          },
          {
            heading: 'Putting everything into one bet',
            body: "It's tempting to go all-in on your highest-conviction idea, but even great companies have bad quarters. Spreading risk across multiple holdings protects you from being wrong about any single company.",
          },
          {
            heading: 'Letting emotions drive decisions',
            body: 'Panic-selling during a dip and euphoria-buying during a rally are two sides of the same trap: reacting to price movement instead of to any actual change in the company. A brief pause before reacting to a big price swing is one of the simplest habits that separates disciplined investors from impulsive ones.',
          },
          {
            heading: 'Ignoring fees and taxes (in the real world)',
            body: "This simulator doesn't charge fees, but real trading does — every trade can carry transaction costs, and in many places selling at a profit triggers taxes. Frequent trading in a real account quietly erodes returns in a way that's easy to overlook.",
          },
        ],
        quiz: [
          {
            question: "What's a risk of buying a stock 'because everyone's talking about it'?",
            options: [
              'There is no risk',
              "You may be buying after the price has already risen on hype that's about to fade",
              'Hype always predicts long-term success',
              'It guarantees a diversified portfolio',
            ],
            correctIndex: 1,
            explanation: "Hype-driven buying often means paying a price that already reflects the excitement — with little room left to gain.",
          },
          {
            question: "What's a healthier response to a sudden, sharp price drop in a stock you hold?",
            options: [
              'Sell immediately without checking anything else',
              'Buy more immediately no matter what',
              'Pause, and consider whether anything about the company actually changed before reacting',
              'Panic',
            ],
            correctIndex: 2,
            explanation: 'Reacting to the price alone — instead of what actually changed about the business — is a common emotional trap.',
          },
        ],
      },
    ],
  },
  {
    id: 'types-of-investments',
    title: 'Types of Investments',
    icon: 'coins',
    lessons: [
      {
        id: 'types-of-stocks',
        title: 'Types of stocks',
        summary: 'Growth vs. value, dividend payers, and company size.',
        sections: [
          {
            heading: 'Growth vs. value',
            body: "Growth stocks belong to companies reinvesting most of their profit back into expanding fast — often young tech companies — which usually means a high price relative to current earnings and little or no dividend. Value stocks trade cheaply relative to their earnings or assets, often because they're more mature, slower-growing businesses the market has priced conservatively. Neither is automatically better; they're different bets on where the return comes from.",
          },
          {
            heading: 'Dividend stocks',
            body: "Some companies pay out a slice of their profit directly to shareholders on a regular schedule — a dividend — instead of reinvesting all of it. That turns part of your return into cash income you receive just for holding the stock, on top of whatever the price does. Dividend yield (annual dividend ÷ price) is the usual way to compare how much income a stock pays relative to its cost.",
          },
          {
            heading: 'Company size',
            body: "Market capitalization (share price × shares outstanding) sorts companies into large-cap (established, generally more stable), mid-cap, and small-cap (younger, more room to grow but usually more volatile). Penny stocks sit at the extreme small end — very low share prices, often thinly traded, and considered especially speculative and risky.",
          },
        ],
        quiz: [
          {
            question: 'What best describes a growth stock?',
            options: [
              'Pays a large, steady dividend and rarely changes price',
              'Reinvests profits to expand quickly, often with a high valuation and little or no dividend',
              'Always the safest choice available',
              'A stock only institutions are allowed to buy',
            ],
            correctIndex: 1,
            explanation: 'Growth companies plow profit back into expansion rather than paying it out, betting on future earnings over current income.',
          },
          {
            question: 'What does market capitalization describe?',
            options: [
              "A company's total number of employees",
              "A company's overall size, based on share price times shares outstanding",
              "A company's annual revenue only",
              "The interest rate on a company's bonds",
            ],
            correctIndex: 1,
            explanation: "Market cap is the market's total valuation of a company's equity — price per share times total shares.",
          },
        ],
      },
      {
        id: 'funds-and-etfs',
        title: 'Funds: mutual funds, index funds & ETFs',
        summary: 'How pooling money into a fund spreads risk automatically.',
        sections: [
          {
            heading: 'What a fund is',
            body: "A fund pools money from many investors to buy a whole basket of stocks, bonds, or other assets at once. Buying a single share of the fund gives you a small slice of everything it holds — instant diversification without having to research and buy each underlying company yourself.",
          },
          {
            heading: 'Mutual funds vs. index funds',
            body: 'A mutual fund can be "actively managed" — a manager picks holdings and trades them, trying to beat the market, usually for a higher annual fee (the "expense ratio"). An index fund instead just tries to mirror a benchmark, like the S&P 500, by holding roughly what that index holds — a passive approach that typically charges a much lower expense ratio.',
          },
          {
            heading: 'ETFs',
            body: "An exchange-traded fund (ETF) is structured like an index or mutual fund — a basket of underlying holdings — but trades all day on an exchange with a live, changing price, just like a stock. A traditional mutual fund, by contrast, is only priced once, after the market closes.",
          },
        ],
        quiz: [
          {
            question: 'What is the main benefit of buying a fund instead of individual stocks?',
            options: [
              'It guarantees a profit',
              'Instant diversification across many holdings in a single purchase',
              'It removes all risk of losing money',
              "It's the only legal way to buy stocks",
            ],
            correctIndex: 1,
            explanation: 'One fund share gives you exposure to everything the fund holds, spreading risk across many positions at once.',
          },
          {
            question: 'What is the key structural difference between an ETF and a traditional mutual fund?',
            options: [
              'ETFs can only hold bonds',
              'An ETF trades throughout the day on an exchange like a stock, while a mutual fund is priced once at the end of the day',
              'Mutual funds never charge any fees',
              'ETFs are riskier by definition',
            ],
            correctIndex: 1,
            explanation: 'ETFs get a live, continuously updated price from exchange trading; mutual funds settle to a single price after the close.',
          },
        ],
      },
      {
        id: 'bonds',
        title: 'Bonds',
        summary: "Lending money for a fixed return, instead of owning a piece of a company.",
        sections: [
          {
            heading: 'What a bond is',
            body: "Buying a stock makes you a part-owner of a company. Buying a bond makes you a lender — to a government or a company — in exchange for regular interest payments and a promise to get your original amount (the principal) back on a set maturity date. A bond is essentially an IOU with a schedule attached.",
          },
          {
            heading: 'Government vs. corporate bonds',
            body: "Government bonds (like U.S. Treasuries) are generally considered very low risk, since they're backed by the government's ability to tax and print currency. Corporate bonds pay a higher interest rate to compensate for the extra risk that a company might struggle to repay — reflected in a credit rating that scores how likely that is.",
          },
          {
            heading: 'Why bonds behave differently from stocks',
            body: "Bond prices tend to move opposite to interest rates — when rates rise, existing bonds paying the old, lower rate become less attractive, so their price falls. Bonds are also usually less volatile day to day than stocks, which is why many portfolios mix in bonds to smooth out swings rather than to chase the highest possible return.",
          },
        ],
        quiz: [
          {
            question: 'When you buy a bond, what are you actually doing?',
            options: [
              'Buying part ownership of a company',
              'Lending money to a government or company in exchange for interest payments',
              "Guaranteeing that company's future profits",
              "Receiving a share of a company's dividends",
            ],
            correctIndex: 1,
            explanation: 'A bond is a loan you make to the issuer, repaid with interest — not an ownership stake.',
          },
          {
            question: 'Why do corporate bonds typically pay a higher interest rate than government bonds?',
            options: [
              'Corporate bonds are simply more popular to trade',
              'To compensate investors for the extra risk that a company might not repay',
              'Governments are not legally allowed to borrow money',
              'There is no real difference between the two',
            ],
            correctIndex: 1,
            explanation: 'Higher perceived default risk gets priced in as a higher interest rate — the reward for taking on more uncertainty.',
          },
        ],
      },
      {
        id: 'other-asset-classes',
        title: 'Other investments: REITs, commodities & crypto',
        summary: 'A quick tour past stocks, funds, and bonds.',
        sections: [
          {
            heading: 'REITs',
            body: "A Real Estate Investment Trust (REIT) lets you invest in income-producing real estate — apartment buildings, malls, warehouses — by buying a stock-like share, without buying and managing property yourself. By law, REITs must pay out most of their income as dividends, which is why they're often used specifically for income.",
          },
          {
            heading: 'Commodities',
            body: "Commodities are raw physical goods — gold, oil, wheat, and the like. Most investors get exposure through specialized funds or ETFs rather than holding the physical good directly. Gold in particular is commonly used as a hedge during inflation or market stress, since it doesn't always move in the same direction as stocks or bonds.",
          },
          {
            heading: 'Cryptocurrency',
            body: "Digital assets like Bitcoin trade continuously and independently of any company's earnings, pay no dividends or interest, and are typically far more volatile than stocks or bonds. Worth understanding as its own distinct, higher-risk category — not a substitute for the core of a diversified portfolio.",
          },
        ],
        quiz: [
          {
            question: 'What is a REIT?',
            options: [
              'A type of government bond',
              'A way to invest in real estate through a stock-like share, without buying property yourself',
              'A cryptocurrency',
              'A fixed-rate savings account',
            ],
            correctIndex: 1,
            explanation: 'REITs package real estate ownership into a tradable share and are required to pass most of their income through as dividends.',
          },
          {
            question: 'Which of these is generally true about cryptocurrency compared to stocks and bonds?',
            options: [
              'It pays a fixed dividend',
              "It's usually far more volatile and doesn't pay interest or dividends",
              'It is backed by a government',
              'It behaves identically to a government bond',
            ],
            correctIndex: 1,
            explanation: 'Crypto has no earnings, interest, or dividends underlying its price, and tends to swing much more than traditional assets.',
          },
        ],
      },
    ],
  },
];
