// Standalone trivia for Speed Round — broader market/finance general
// knowledge than the Learn lessons' own quiz questions (which SpeedRoundGame
// also pulls in), so a fast player cycling through the pool hits more
// variety before questions repeat.
export const SPEED_ROUND_EXTRA_QUESTIONS = [
  {
    question: 'What does IPO stand for?',
    options: ['International Pricing Order', 'Initial Public Offering', 'Investor Payout Option', 'Index Price Overview'],
    correctIndex: 1,
    explanation: 'An IPO is when a company sells shares to the public for the first time.',
  },
  {
    question: "What is a 'bull market'?",
    options: ['A period of falling prices', 'A period of rising prices', 'A market with no trading', 'A market only for bonds'],
    correctIndex: 1,
    explanation: 'A bull market describes a sustained period of rising prices.',
  },
  {
    question: "What is a 'bear market'?",
    options: ['A period of rising prices', 'A market only open on weekends', 'A sustained period of falling prices', 'A market with fixed prices'],
    correctIndex: 2,
    explanation: 'A bear market describes a sustained period of falling prices.',
  },
  {
    question: 'What does NYSE stand for?',
    options: ['New York Securities Exchange', 'National Yield Stock Exchange', 'New York Stock Exchange', 'North York Stock Exchange'],
    correctIndex: 2,
    explanation: 'NYSE is the New York Stock Exchange, one of the largest exchanges in the world.',
  },
  {
    question: 'What is the S&P 500?',
    options: [
      'A single company',
      'An index tracking 500 large U.S. companies',
      'A type of bond',
      "A government agency",
    ],
    correctIndex: 1,
    explanation: 'The S&P 500 is a widely-followed index of 500 large publicly traded U.S. companies.',
  },
  {
    question: 'The Dow Jones Industrial Average tracks how many companies?',
    options: ['10', '30', '100', '500'],
    correctIndex: 1,
    explanation: 'The Dow tracks 30 large, well-established U.S. companies.',
  },
  {
    question: "What is a 'blue-chip' stock?",
    options: [
      'A newly listed, unproven company',
      'A stock that only trades on weekends',
      'Stock of a large, well-established, financially sound company',
      'A stock priced under $1',
    ],
    correctIndex: 2,
    explanation: 'Blue-chip stocks belong to large, stable, reputable companies with a long track record.',
  },
  {
    question: 'What does the P/E ratio stand for?',
    options: ['Profit/Equity ratio', 'Price-to-Earnings ratio', 'Payout/Expense ratio', 'Principal/Estimate ratio'],
    correctIndex: 1,
    explanation: 'P/E ratio compares a stock\'s price to its earnings per share.',
  },
  {
    question: 'What does a high P/E ratio typically suggest about a stock?',
    options: [
      'Investors expect little future growth',
      'The company is bankrupt',
      'Investors expect higher future growth',
      'The stock pays a huge dividend',
    ],
    correctIndex: 2,
    explanation: "A high P/E often means investors are paying more today for earnings they expect to grow.",
  },
  {
    question: "What does 'market capitalization' measure?",
    options: [
      "A company's total debt",
      "The total value of a company's outstanding shares",
      "A company's yearly revenue",
      'The number of employees at a company',
    ],
    correctIndex: 1,
    explanation: 'Market cap = share price × total shares outstanding.',
  },
  {
    question: "What is 'short selling'?",
    options: [
      'Buying a stock and holding it briefly',
      'Selling borrowed shares, betting the price will fall',
      'Selling only fractional shares',
      'A type of dividend payment',
    ],
    correctIndex: 1,
    explanation: 'Short sellers borrow shares to sell now, hoping to buy them back cheaper later.',
  },
  {
    question: 'What is compound interest?',
    options: [
      'Interest paid only once, at the end',
      'Interest calculated only on the original principal',
      'Interest calculated on both principal and previously earned interest',
      'A fee charged for early withdrawal',
    ],
    correctIndex: 2,
    explanation: "Compound interest lets your earnings themselves start earning, snowballing over time.",
  },
  {
    question: 'What is inflation?',
    options: [
      'A general rise in prices that reduces purchasing power over time',
      'A guaranteed increase in stock prices',
      'A tax on capital gains',
      'A type of interest rate set by banks',
    ],
    correctIndex: 0,
    explanation: 'Inflation erodes how much your money can buy as prices rise across the economy.',
  },
  {
    question: "What does a stock's '52-week high' mean?",
    options: [
      'The price it will reach next year',
      'The highest price it has traded at in the past year',
      'The average price over 52 weeks',
      'The price on the day it IPO\'d',
    ],
    correctIndex: 1,
    explanation: "It's simply the highest trading price recorded over the trailing 52 weeks.",
  },
  {
    question: "What is the 'ex-dividend date'?",
    options: [
      'The date a company goes public',
      'The date after which a new buyer no longer receives the upcoming dividend',
      'The date dividends are always paid',
      'The last day a stock can be traded',
    ],
    correctIndex: 1,
    explanation: 'Buy on or after the ex-dividend date, and the upcoming dividend goes to the previous owner instead.',
  },
  {
    question: "What does 'going public' mean for a company?",
    options: [
      'Announcing quarterly earnings',
      'Selling shares to the public for the first time via an IPO',
      'Merging with a competitor',
      'Filing for bankruptcy',
    ],
    correctIndex: 1,
    explanation: 'Going public is another way of describing a company\'s IPO.',
  },
  {
    question: "What happens in a 2-for-1 stock split?",
    options: [
      'The company merges with another',
      'Each share becomes two shares, and the price per share roughly halves',
      'Half the shareholders are bought out',
      'The dividend doubles',
    ],
    correctIndex: 1,
    explanation: "A split increases share count and lowers price per share proportionally — total value is unchanged.",
  },
  {
    question: 'What is the ticker symbol for Apple?',
    options: ['APPL', 'AAPL', 'APL', 'AAPLE'],
    correctIndex: 1,
    explanation: "Apple trades under the ticker AAPL.",
  },
  {
    question: 'What is the ticker symbol for Amazon?',
    options: ['AMZN', 'AMZ', 'AMAZ', 'AZN'],
    correctIndex: 0,
    explanation: 'Amazon trades under the ticker AMZN.',
  },
  {
    question: 'What is the ticker symbol for Tesla?',
    options: ['TESL', 'TSLA', 'TSL', 'TDA'],
    correctIndex: 1,
    explanation: 'Tesla trades under the ticker TSLA.',
  },
  {
    question: 'Which exchange is famous for its trading floor and opening/closing bell tradition?',
    options: ['NASDAQ', 'NYSE', 'LSE', 'TSX'],
    correctIndex: 1,
    explanation: 'The NYSE is known for its physical trading floor and the daily bell-ringing ceremony.',
  },
  {
    question: "What does 'liquidity' mean for an investment?",
    options: [
      'How much it pays in dividends',
      'How easily it can be bought or sold without moving its price much',
      'How volatile its price is',
      'How old the company is',
    ],
    correctIndex: 1,
    explanation: 'A highly liquid asset can be traded quickly, in size, without significantly moving the price.',
  },
  {
    question: "What is a 'penny stock'?",
    options: [
      'A stock that only costs one cent to trade',
      'A low-priced, often thinly traded and highly speculative stock',
      'A stock issued by a coin company',
      'A stock guaranteed by the government',
    ],
    correctIndex: 1,
    explanation: 'Penny stocks trade at very low prices and carry outsized risk and volatility.',
  },
  {
    question: "What does 'going long' on a stock mean?",
    options: [
      'Holding a stock for at least 10 years',
      'Buying an asset, expecting its price to rise',
      'Betting an asset\'s price will fall',
      'Buying on margin only',
    ],
    correctIndex: 1,
    explanation: 'Going long is simply owning an asset in the hope it appreciates.',
  },
  {
    question: "What is a 'margin account'?",
    options: [
      'An account that pays no interest',
      'A brokerage account that lets you borrow money to trade',
      'An account only for retirement savings',
      'An account that can only hold cash',
    ],
    correctIndex: 1,
    explanation: 'Margin accounts let investors borrow against their holdings to increase buying power — and risk.',
  },
  {
    question: "What is the main goal of diversification?",
    options: [
      'To guarantee a profit',
      'To reduce the impact any single investment can have on your portfolio',
      'To avoid paying any taxes',
      'To increase trading fees',
    ],
    correctIndex: 1,
    explanation: 'Spreading investments around limits how much damage any one holding can do.',
  },
  {
    question: "What is an 'expense ratio'?",
    options: [
      'A one-time fee to open a brokerage account',
      'The annual fee a fund charges, as a percentage of assets',
      'The tax rate on capital gains',
      'A penalty for selling too early',
    ],
    correctIndex: 1,
    explanation: "A fund's expense ratio is deducted annually to cover its operating costs.",
  },
  {
    question: "In financial news, 'the Fed' usually refers to what?",
    options: ['A federal tax office', 'The Federal Reserve, the U.S. central bank', 'A stock exchange', 'A credit rating agency'],
    correctIndex: 1,
    explanation: 'The Federal Reserve sets U.S. monetary policy, including interest rates.',
  },
  {
    question: "What is a 'recession'?",
    options: [
      'A single bad trading day',
      'A significant decline in economic activity over a sustained period',
      'A type of stock order',
      'A tax on investment income',
    ],
    correctIndex: 1,
    explanation: "A recession is a broad, sustained economic downturn, not a single market event.",
  },
  {
    question: "What does 'volatility' measure?",
    options: [
      'A company\'s total debt',
      'How much and how fast a price swings up and down',
      'The dividend yield',
      'The number of shares outstanding',
    ],
    correctIndex: 1,
    explanation: 'Volatility measures the size and speed of price movements, not their direction.',
  },
  {
    question: "What is a 'stop-loss' order commonly used for?",
    options: [
      'Guaranteeing a profit',
      'Automatically limiting further losses if a price falls to a set level',
      'Avoiding all trading fees',
      'Doubling a position size',
    ],
    correctIndex: 1,
    explanation: 'A stop-loss triggers a sale once a price drops to a set level, capping further downside.',
  },
  {
    question: "What best describes an ETF?",
    options: [
      'A single company\'s stock',
      'A fund that trades on an exchange throughout the day like a stock',
      'A type of government bond',
      'A savings account with a fixed rate',
    ],
    correctIndex: 1,
    explanation: 'ETFs hold a basket of assets but trade all day on an exchange, like an individual stock.',
  },
  {
    question: "What is a company's 'book value'?",
    options: [
      'Its stock price times shares outstanding',
      "Its assets minus its liabilities",
      'Its total annual revenue',
      'The price it IPO\'d at',
    ],
    correctIndex: 1,
    explanation: "Book value reflects what's left for shareholders if a company's assets covered all its debts.",
  },
  {
    question: "What does it mean when a stock 'gaps up'?",
    options: [
      'It stops trading entirely',
      'It opens noticeably higher than where it closed the previous session',
      'It splits into two stocks',
      'It gets removed from an index',
    ],
    correctIndex: 1,
    explanation: 'A gap up means the opening price jumps well above the prior close, often on overnight news.',
  },
  {
    question: "What is a 'sector' in investing?",
    options: [
      'A single stock',
      'A group of companies operating in a similar area of the economy (e.g. tech, healthcare)',
      'A type of bond',
      'A government regulatory body',
    ],
    correctIndex: 1,
    explanation: 'Sectors group companies by the kind of business they\'re in, useful for diversifying across industries.',
  },
  {
    question: "What does 'yield' generally refer to for an investment?",
    options: [
      'The total number of shares issued',
      'The income (like dividends or interest) it generates, often as a percentage of price',
      'The company\'s market capitalization',
      'How long you\'ve held it',
    ],
    correctIndex: 1,
    explanation: 'Yield expresses income generated relative to the price paid — for example, dividend yield.',
  },
  {
    question: "What is an 'index'?",
    options: [
      'A single stock traded on an exchange',
      'A statistical measure tracking the performance of a group of assets',
      'A type of brokerage account',
      'A government tax form',
    ],
    correctIndex: 1,
    explanation: "Indexes like the S&P 500 track a basket of securities to represent a market or sector's performance.",
  },
  {
    question: "What is a company's 'earnings report' primarily used to communicate?",
    options: [
      'Its stock ticker symbol',
      'Its financial performance over a recent period, like revenue and profit',
      'Its CEO\'s salary only',
      'Its stock split schedule',
    ],
    correctIndex: 1,
    explanation: 'Earnings reports summarize how a company performed financially over the quarter or year.',
  },
  {
    question: "What is a 'dividend yield'?",
    options: [
      'The total dollar amount of dividends ever paid',
      "A stock's annual dividend divided by its current price",
      'The tax rate on dividends',
      'The number of shareholders receiving dividends',
    ],
    correctIndex: 1,
    explanation: 'Dividend yield expresses the dividend as a percentage of the current share price.',
  },
  {
    question: "What is 'asset allocation'?",
    options: [
      'Picking a single best stock',
      'How you divide your money across different investment categories, like stocks and bonds',
      'The process of selling all your holdings',
      'A type of brokerage fee',
    ],
    correctIndex: 1,
    explanation: 'Asset allocation is the mix of asset types (stocks, bonds, cash, etc.) that makes up a portfolio.',
  },
  {
    question: "What is 'dollar-cost averaging'?",
    options: [
      'Investing a fixed amount at regular intervals, regardless of price',
      'Only buying stocks priced under $1',
      'Converting all holdings to cash once a year',
      'Averaging the prices of two different currencies',
    ],
    correctIndex: 0,
    explanation: 'Investing a fixed amount on a schedule smooths out the effect of buying at any single price.',
  },
  {
    question: "What does 'rebalancing' a portfolio mean?",
    options: [
      'Selling everything and starting over',
      'Adjusting holdings back toward a target allocation',
      'Only investing in bonds',
      'Closing your brokerage account',
    ],
    correctIndex: 1,
    explanation: 'Rebalancing trims positions that have grown too large and tops up ones that have shrunk, restoring the intended mix.',
  },
  {
    question: 'What is a 401(k)?',
    options: [
      'A type of stock index',
      'An employer-sponsored retirement savings plan',
      'A government bond',
      'A brokerage trading fee',
    ],
    correctIndex: 1,
    explanation: 'A 401(k) is a workplace retirement account, often with employer-matched contributions.',
  },
  {
    question: 'A Roth IRA is best known for which feature?',
    options: [
      'Contributions are tax-deductible now, and withdrawals are taxed later',
      'Contributions are made after tax, and qualified withdrawals in retirement are tax-free',
      'It can only hold cash',
      'It has no contribution limits',
    ],
    correctIndex: 1,
    explanation: "Roth accounts flip the usual order: pay tax now, so qualified withdrawals later come out tax-free.",
  },
  {
    question: 'Which U.S. government agency primarily regulates securities markets?',
    options: ['The IRS', 'The SEC (Securities and Exchange Commission)', 'The FDA', 'The Department of Labor'],
    correctIndex: 1,
    explanation: 'The SEC oversees securities markets and enforces rules to protect investors.',
  },
  {
    question: 'What does FDIC insurance protect?',
    options: [
      'Stock market losses',
      'Bank deposits, up to a coverage limit, if the bank fails',
      'Cryptocurrency held in a wallet',
      'Losses on bond investments',
    ],
    correctIndex: 1,
    explanation: 'FDIC insurance covers bank deposits — it has nothing to do with stock market investment losses.',
  },
  {
    question: "What is 'insider trading'?",
    options: [
      'Trading only within your own brokerage app',
      'Trading a stock based on material, non-public information — generally illegal',
      'Trading between employees of the same company',
      'A legal strategy used by mutual funds',
    ],
    correctIndex: 1,
    explanation: 'Trading on material non-public information gives an unfair advantage and is illegal in most markets.',
  },
  {
    question: 'What is day trading?',
    options: [
      'Holding an investment for exactly one year',
      'Buying and selling securities within the same trading day',
      'Only trading on the first day of the month',
      'A synonym for long-term investing',
    ],
    correctIndex: 1,
    explanation: 'Day traders open and close positions before the market closes the same day.',
  },
  {
    question: 'What best describes a swing trade?',
    options: [
      'Holding a position for years',
      'Holding a position for days to weeks to capture a short-term price move',
      'A trade that never closes',
      'A type of dividend payment',
    ],
    correctIndex: 1,
    explanation: 'Swing trading sits between day trading and long-term investing, holding positions over a short stretch of time.',
  },
  {
    question: "What does 'buy and hold' describe?",
    options: [
      'Buying an investment and holding it long-term through short-term swings',
      'Buying and selling the same day',
      'Only buying stocks that pay dividends',
      'A rule requiring you to hold cash only',
    ],
    correctIndex: 0,
    explanation: 'Buy and hold favors staying invested over time instead of reacting to short-term price moves.',
  },
  {
    question: "What is a 'robo-advisor'?",
    options: [
      'A physical ATM for trading stocks',
      'An automated platform that builds and manages a portfolio for you',
      'A type of high-frequency trading bot banned by regulators',
      'A chatbot that only answers customer service questions',
    ],
    correctIndex: 1,
    explanation: 'Robo-advisors use algorithms to build and rebalance a portfolio based on your goals and risk tolerance.',
  },
  {
    question: "What is a 'target-date fund'?",
    options: [
      'A fund that only invests in one company',
      'A fund that automatically shifts its allocation as a target year (like retirement) approaches',
      'A fund with a fixed, unchanging allocation forever',
      'A fund that closes on a specific date',
    ],
    correctIndex: 1,
    explanation: 'Target-date funds gradually become more conservative as the target year gets closer.',
  },
  {
    question: 'What does EPS (earnings per share) measure?',
    options: [
      "A company's total revenue",
      "A company's profit divided by its number of outstanding shares",
      'The price of one share',
      "A company's total debt per employee",
    ],
    correctIndex: 1,
    explanation: 'EPS shows how much profit is attributable to each individual share.',
  },
  {
    question: "What does a stock 'buyback' (share repurchase) do?",
    options: [
      'Issues new shares to raise cash',
      'The company buys its own shares, reducing the number outstanding',
      'Forces existing shareholders to sell',
      'Splits each share into two',
    ],
    correctIndex: 1,
    explanation: 'Buybacks reduce share count, which can raise per-share metrics like EPS.',
  },
  {
    question: "What is a company's 'moat' in investing terms?",
    options: [
      'Its cash reserves',
      'A durable competitive advantage that protects it from rivals',
      'A type of bond it issues',
      'A physical office building',
    ],
    correctIndex: 1,
    explanation: "A moat — brand, network effects, patents, scale — helps a company defend its profits from competitors.",
  },
  {
    question: 'The acronym "FAANG" originally referred to which group of companies?',
    options: [
      'Five major airline companies',
      'Facebook, Apple, Amazon, Netflix, and Google',
      'Five central banks',
      'A group of oil companies',
    ],
    correctIndex: 1,
    explanation: 'FAANG became shorthand for a handful of dominant, high-growth U.S. tech companies.',
  },
  {
    question: "What does 'Wall Street' commonly refer to?",
    options: [
      'A single company',
      'The U.S. financial industry and markets broadly',
      'A type of bond',
      'A government regulator',
    ],
    correctIndex: 1,
    explanation: "Wall Street (a real street in Manhattan) is used as shorthand for the broader U.S. financial industry.",
  },
  {
    question: 'When does the NYSE regular trading session typically open?',
    options: ['6:00 a.m. Eastern', '9:30 a.m. Eastern', '12:00 p.m. Eastern', '4:00 p.m. Eastern'],
    correctIndex: 1,
    explanation: 'The NYSE regular session runs 9:30 a.m. to 4:00 p.m. Eastern Time on trading days.',
  },
  {
    question: "What is 'after-hours trading'?",
    options: [
      'Trading that happens after the regular session closes',
      'A trading session only for bonds',
      'Illegal trading activity',
      'Trading that only banks can do',
    ],
    correctIndex: 0,
    explanation: 'After-hours trading lets investors trade once the regular session ends, though with thinner liquidity.',
  },
  {
    question: "What is a 'dead cat bounce'?",
    options: [
      'A guaranteed sign of a full recovery',
      'A brief, misleading price recovery during an overall downtrend',
      'A type of dividend increase',
      'A required trading halt',
    ],
    correctIndex: 1,
    explanation: 'A dead cat bounce looks like a recovery but is often just a temporary pause within a larger decline.',
  },
  {
    question: 'FOMO (fear of missing out) often leads investors to do what?',
    options: [
      'Sell everything and hold cash',
      'Buy an asset impulsively because its price is rising fast',
      'Diversify more carefully',
      'Wait patiently for lower prices',
    ],
    correctIndex: 1,
    explanation: 'FOMO can push investors to chase a rally rather than sticking to a plan.',
  },
  {
    question: 'What is a hedge fund?',
    options: [
      'A retirement account for teachers',
      'A pooled investment fund using varied, often aggressive strategies, typically for institutional or accredited investors',
      'A government savings bond',
      'A type of index fund available to anyone',
    ],
    correctIndex: 1,
    explanation: 'Hedge funds pursue a wide range of strategies and are generally less accessible and less regulated than mutual funds.',
  },
  {
    question: 'What is venture capital used for?',
    options: [
      'Funding early-stage, high-growth startups',
      'Insuring bank deposits',
      'Buying government bonds only',
      'Paying corporate dividends',
    ],
    correctIndex: 0,
    explanation: 'Venture capital firms invest in young companies with high growth potential in exchange for equity.',
  },
  {
    question: 'What is an angel investor?',
    options: [
      'A government regulator',
      'An individual who invests personal funds in early-stage startups',
      'A type of mutual fund',
      'A stock exchange employee',
    ],
    correctIndex: 1,
    explanation: 'Angel investors are individuals, often with their own money, backing very early-stage companies.',
  },
  {
    question: "What does 'unicorn' mean in the startup world?",
    options: [
      'A company that has gone bankrupt',
      'A private startup valued at $1 billion or more',
      'A publicly traded company',
      'A company with no employees',
    ],
    correctIndex: 1,
    explanation: 'Unicorn is startup jargon for a privately held company valued at $1B+.',
  },
  {
    question: "What is an IPO 'lock-up period'?",
    options: [
      'The window before an IPO when no one can buy shares',
      'A window after an IPO when insiders are restricted from selling their shares',
      'A permanent ban on selling shares',
      'The time it takes to open a brokerage account',
    ],
    correctIndex: 1,
    explanation: 'Lock-up periods prevent early investors and employees from immediately dumping shares after an IPO.',
  },
  {
    question: 'What does Nasdaq primarily consist of?',
    options: [
      'A physical trading floor with no computers',
      'A fully electronic stock exchange',
      'A government bond marketplace',
      'A private members-only club',
    ],
    correctIndex: 1,
    explanation: "Unlike the NYSE's physical floor, Nasdaq has operated as an electronic exchange from the start.",
  },
  {
    question: 'What does the "S" in S&P 500 stand for?',
    options: ['Stock', 'Standard (from Standard & Poor\'s)', 'Sector', 'Securities'],
    correctIndex: 1,
    explanation: 'S&P stands for Standard & Poor\'s, the financial company that maintains the index.',
  },
  {
    question: "What is a company's '10-K' filing?",
    options: [
      'A quarterly earnings press release only',
      "A detailed annual report filed with securities regulators",
      'A stock split announcement',
      'A form used only to change a company\'s ticker symbol',
    ],
    correctIndex: 1,
    explanation: 'The 10-K is a comprehensive annual filing covering financials, risks, and operations.',
  },
  {
    question: "What is 'quarterly earnings season'?",
    options: [
      'A holiday for stock exchanges',
      'The period when most public companies report results for the past quarter',
      'The four weeks before an IPO',
      'A tax filing deadline',
    ],
    correctIndex: 1,
    explanation: 'Earnings season is when companies cluster their quarterly financial reporting, often moving prices sharply.',
  },
  {
    question: 'Capital gains tax generally applies to what?',
    options: [
      'Money kept in a savings account',
      'Profit made from selling an investment for more than you paid',
      'Money spent on rent',
      'Salary income only',
    ],
    correctIndex: 1,
    explanation: 'Capital gains tax is owed on the profit realized when you sell an investment above its cost basis.',
  },
  {
    question: 'What distinguishes long-term from short-term capital gains?',
    options: [
      'The size of the gain in dollars',
      'How long the asset was held before it was sold',
      'Whether the company pays a dividend',
      'The exchange the stock trades on',
    ],
    correctIndex: 1,
    explanation: 'Tax rules typically define a holding-period threshold that separates long-term from short-term gains.',
  },
  {
    question: 'What is a "wash sale"?',
    options: [
      'Selling all your holdings for cash',
      'Selling a security at a loss and buying a substantially similar one shortly after',
      'A trade that fails to execute',
      'A dividend reinvestment plan',
    ],
    correctIndex: 1,
    explanation: 'Wash sale rules can disallow claiming a tax loss if you buy back a near-identical position too soon.',
  },
  {
    question: 'What does ESG investing consider, alongside financial returns?',
    options: [
      'Environmental, social, and governance factors',
      'Only a company\'s stock price history',
      'Only executive salaries',
      'Only a company\'s headquarters location',
    ],
    correctIndex: 0,
    explanation: 'ESG investing weighs environmental, social, and governance criteria alongside financial performance.',
  },
  {
    question: "What is a company's 'float'?",
    options: [
      'Its total number of employees',
      'The number of shares actually available for public trading',
      'Its total debt',
      'A type of bond',
    ],
    correctIndex: 1,
    explanation: 'Float excludes closely-held or restricted shares, counting only what actively trades in the market.',
  },
  {
    question: 'What is the ticker symbol for Alphabet (Google)?',
    options: ['GOOG', 'GOOGL', 'ALPH', 'GGL'],
    correctIndex: 1,
    explanation: 'Alphabet\'s Class A shares trade under GOOGL (GOOG is the non-voting Class C).',
  },
  {
    question: 'What is the ticker symbol for Meta (Facebook)?',
    options: ['FB', 'META', 'METAP', 'FCBK'],
    correctIndex: 1,
    explanation: 'Facebook\'s parent company changed its ticker to META in 2022.',
  },
  {
    question: 'What is the ticker symbol for JPMorgan Chase?',
    options: ['JPM', 'JPC', 'CHASE', 'JMC'],
    correctIndex: 0,
    explanation: 'JPMorgan Chase trades under the ticker JPM.',
  },
  {
    question: 'What is the ticker symbol for Visa?',
    options: ['VISA', 'V', 'VSA', 'VZ'],
    correctIndex: 1,
    explanation: 'Visa trades under the simple single-letter ticker V.',
  },
  {
    question: 'What is the ticker symbol for Walmart?',
    options: ['WMT', 'WALM', 'WM', 'WAL'],
    correctIndex: 0,
    explanation: 'Walmart trades under the ticker WMT.',
  },
];
