// Standalone trivia for Speed Round — broader market/finance general
// knowledge than the Learn lessons' own quiz questions (which SpeedRoundGame
// also pulls in), so a fast player cycling through the pool hits more
// variety before questions repeat.
export const SPEED_ROUND_EXTRA_QUESTIONS = [
  {
    question: 'What does IPO stand for?',
    options: ['International Pricing Order', 'Initial Public Offering', 'Investor Payout Option', 'Index Price Overview'],
    correctIndex: 1,
    explanation: 'An IPO is when a company sells shares to the public for the first time.',
  },
  {
    question: "What is a 'bull market'?",
    options: ['A period of falling prices', 'A period of rising prices', 'A market with no trading', 'A market only for bonds'],
    correctIndex: 1,
    explanation: 'A bull market describes a sustained period of rising prices.',
  },
  {
    question: "What is a 'bear market'?",
    options: ['A period of rising prices', 'A market only open on weekends', 'A sustained period of falling prices', 'A market with fixed prices'],
    correctIndex: 2,
    explanation: 'A bear market describes a sustained period of falling prices.',
  },
  {
    question: 'What does NYSE stand for?',
    options: ['New York Securities Exchange', 'National Yield Stock Exchange', 'New York Stock Exchange', 'North York Stock Exchange'],
    correctIndex: 2,
    explanation: 'NYSE is the New York Stock Exchange, one of the largest exchanges in the world.',
  },
  {
    question: 'What is the S&P 500?',
    options: [
      'A single company',
      'An index tracking 500 large U.S. companies',
      'A type of bond',
      "A government agency",
    ],
    correctIndex: 1,
    explanation: 'The S&P 500 is a widely-followed index of 500 large publicly traded U.S. companies.',
  },
  {
    question: 'The Dow Jones Industrial Average tracks how many companies?',
    options: ['10', '30', '100', '500'],
    correctIndex: 1,
    explanation: 'The Dow tracks 30 large, well-established U.S. companies.',
  },
  {
    question: "What is a 'blue-chip' stock?",
    options: [
      'A newly listed, unproven company',
      'A stock that only trades on weekends',
      'Stock of a large, well-established, financially sound company',
      'A stock priced under $1',
    ],
    correctIndex: 2,
    explanation: 'Blue-chip stocks belong to large, stable, reputable companies with a long track record.',
  },
  {
    question: 'What does the P/E ratio stand for?',
    options: ['Profit/Equity ratio', 'Price-to-Earnings ratio', 'Payout/Expense ratio', 'Principal/Estimate ratio'],
    correctIndex: 1,
    explanation: 'P/E ratio compares a stock\'s price to its earnings per share.',
  },
  {
    question: 'What does a high P/E ratio typically suggest about a stock?',
    options: [
      'Investors expect little future growth',
      'The company is bankrupt',
      'Investors expect higher future growth',
      'The stock pays a huge dividend',
    ],
    correctIndex: 2,
    explanation: "A high P/E often means investors are paying more today for earnings they expect to grow.",
  },
  {
    question: "What does 'market capitalization' measure?",
    options: [
      "A company's total debt",
      "The total value of a company's outstanding shares",
      "A company's yearly revenue",
      'The number of employees at a company',
    ],
    correctIndex: 1,
    explanation: 'Market cap = share price × total shares outstanding.',
  },
  {
    question: "What is 'short selling'?",
    options: [
      'Buying a stock and holding it briefly',
      'Selling borrowed shares, betting the price will fall',
      'Selling only fractional shares',
      'A type of dividend payment',
    ],
    correctIndex: 1,
    explanation: 'Short sellers borrow shares to sell now, hoping to buy them back cheaper later.',
  },
  {
    question: 'What is compound interest?',
    options: [
      'Interest paid only once, at the end',
      'Interest calculated only on the original principal',
      'Interest calculated on both principal and previously earned interest',
      'A fee charged for early withdrawal',
    ],
    correctIndex: 2,
    explanation: "Compound interest lets your earnings themselves start earning, snowballing over time.",
  },
  {
    question: 'What is inflation?',
    options: [
      'A general rise in prices that reduces purchasing power over time',
      'A guaranteed increase in stock prices',
      'A tax on capital gains',
      'A type of interest rate set by banks',
    ],
    correctIndex: 0,
    explanation: 'Inflation erodes how much your money can buy as prices rise across the economy.',
  },
  {
    question: "What does a stock's '52-week high' mean?",
    options: [
      'The price it will reach next year',
      'The highest price it has traded at in the past year',
      'The average price over 52 weeks',
      'The price on the day it IPO\'d',
    ],
    correctIndex: 1,
    explanation: "It's simply the highest trading price recorded over the trailing 52 weeks.",
  },
  {
    question: "What is the 'ex-dividend date'?",
    options: [
      'The date a company goes public',
      'The date after which a new buyer no longer receives the upcoming dividend',
      'The date dividends are always paid',
      'The last day a stock can be traded',
    ],
    correctIndex: 1,
    explanation: 'Buy on or after the ex-dividend date, and the upcoming dividend goes to the previous owner instead.',
  },
  {
    question: "What does 'going public' mean for a company?",
    options: [
      'Announcing quarterly earnings',
      'Selling shares to the public for the first time via an IPO',
      'Merging with a competitor',
      'Filing for bankruptcy',
    ],
    correctIndex: 1,
    explanation: 'Going public is another way of describing a company\'s IPO.',
  },
  {
    question: "What happens in a 2-for-1 stock split?",
    options: [
      'The company merges with another',
      'Each share becomes two shares, and the price per share roughly halves',
      'Half the shareholders are bought out',
      'The dividend doubles',
    ],
    correctIndex: 1,
    explanation: "A split increases share count and lowers price per share proportionally — total value is unchanged.",
  },
  {
    question: 'What is the ticker symbol for Apple?',
    options: ['APPL', 'AAPL', 'APL', 'AAPLE'],
    correctIndex: 1,
    explanation: "Apple trades under the ticker AAPL.",
  },
  {
    question: 'What is the ticker symbol for Amazon?',
    options: ['AMZN', 'AMZ', 'AMAZ', 'AZN'],
    correctIndex: 0,
    explanation: 'Amazon trades under the ticker AMZN.',
  },
  {
    question: 'What is the ticker symbol for Tesla?',
    options: ['TESL', 'TSLA', 'TSL', 'TDA'],
    correctIndex: 1,
    explanation: 'Tesla trades under the ticker TSLA.',
  },
  {
    question: 'Which exchange is famous for its trading floor and opening/closing bell tradition?',
    options: ['NASDAQ', 'NYSE', 'LSE', 'TSX'],
    correctIndex: 1,
    explanation: 'The NYSE is known for its physical trading floor and the daily bell-ringing ceremony.',
  },
  {
    question: "What does 'liquidity' mean for an investment?",
    options: [
      'How much it pays in dividends',
      'How easily it can be bought or sold without moving its price much',
      'How volatile its price is',
      'How old the company is',
    ],
    correctIndex: 1,
    explanation: 'A highly liquid asset can be traded quickly, in size, without significantly moving the price.',
  },
  {
    question: "What is a 'penny stock'?",
    options: [
      'A stock that only costs one cent to trade',
      'A low-priced, often thinly traded and highly speculative stock',
      'A stock issued by a coin company',
      'A stock guaranteed by the government',
    ],
    correctIndex: 1,
    explanation: 'Penny stocks trade at very low prices and carry outsized risk and volatility.',
  },
  {
    question: "What does 'going long' on a stock mean?",
    options: [
      'Holding a stock for at least 10 years',
      'Buying an asset, expecting its price to rise',
      'Betting an asset\'s price will fall',
      'Buying on margin only',
    ],
    correctIndex: 1,
    explanation: 'Going long is simply owning an asset in the hope it appreciates.',
  },
  {
    question: "What is a 'margin account'?",
    options: [
      'An account that pays no interest',
      'A brokerage account that lets you borrow money to trade',
      'An account only for retirement savings',
      'An account that can only hold cash',
    ],
    correctIndex: 1,
    explanation: 'Margin accounts let investors borrow against their holdings to increase buying power — and risk.',
  },
  {
    question: "What is the main goal of diversification?",
    options: [
      'To guarantee a profit',
      'To reduce the impact any single investment can have on your portfolio',
      'To avoid paying any taxes',
      'To increase trading fees',
    ],
    correctIndex: 1,
    explanation: 'Spreading investments around limits how much damage any one holding can do.',
  },
  {
    question: "What is an 'expense ratio'?",
    options: [
      'A one-time fee to open a brokerage account',
      'The annual fee a fund charges, as a percentage of assets',
      'The tax rate on capital gains',
      'A penalty for selling too early',
    ],
    correctIndex: 1,
    explanation: "A fund's expense ratio is deducted annually to cover its operating costs.",
  },
  {
    question: "In financial news, 'the Fed' usually refers to what?",
    options: ['A federal tax office', 'The Federal Reserve, the U.S. central bank', 'A stock exchange', 'A credit rating agency'],
    correctIndex: 1,
    explanation: 'The Federal Reserve sets U.S. monetary policy, including interest rates.',
  },
  {
    question: "What is a 'recession'?",
    options: [
      'A single bad trading day',
      'A significant decline in economic activity over a sustained period',
      'A type of stock order',
      'A tax on investment income',
    ],
    correctIndex: 1,
    explanation: "A recession is a broad, sustained economic downturn, not a single market event.",
  },
  {
    question: "What does 'volatility' measure?",
    options: [
      'A company\'s total debt',
      'How much and how fast a price swings up and down',
      'The dividend yield',
      'The number of shares outstanding',
    ],
    correctIndex: 1,
    explanation: 'Volatility measures the size and speed of price movements, not their direction.',
  },
  {
    question: "What is a 'stop-loss' order commonly used for?",
    options: [
      'Guaranteeing a profit',
      'Automatically limiting further losses if a price falls to a set level',
      'Avoiding all trading fees',
      'Doubling a position size',
    ],
    correctIndex: 1,
    explanation: 'A stop-loss triggers a sale once a price drops to a set level, capping further downside.',
  },
  {
    question: "What best describes an ETF?",
    options: [
      'A single company\'s stock',
      'A fund that trades on an exchange throughout the day like a stock',
      'A type of government bond',
      'A savings account with a fixed rate',
    ],
    correctIndex: 1,
    explanation: 'ETFs hold a basket of assets but trade all day on an exchange, like an individual stock.',
  },
  {
    question: "What is a company's 'book value'?",
    options: [
      'Its stock price times shares outstanding',
      "Its assets minus its liabilities",
      'Its total annual revenue',
      'The price it IPO\'d at',
    ],
    correctIndex: 1,
    explanation: "Book value reflects what's left for shareholders if a company's assets covered all its debts.",
  },
  {
    question: "What does it mean when a stock 'gaps up'?",
    options: [
      'It stops trading entirely',
      'It opens noticeably higher than where it closed the previous session',
      'It splits into two stocks',
      'It gets removed from an index',
    ],
    correctIndex: 1,
    explanation: 'A gap up means the opening price jumps well above the prior close, often on overnight news.',
  },
  {
    question: "What is a 'sector' in investing?",
    options: [
      'A single stock',
      'A group of companies operating in a similar area of the economy (e.g. tech, healthcare)',
      'A type of bond',
      'A government regulatory body',
    ],
    correctIndex: 1,
    explanation: 'Sectors group companies by the kind of business they\'re in, useful for diversifying across industries.',
  },
  {
    question: "What does 'yield' generally refer to for an investment?",
    options: [
      'The total number of shares issued',
      'The income (like dividends or interest) it generates, often as a percentage of price',
      'The company\'s market capitalization',
      'How long you\'ve held it',
    ],
    correctIndex: 1,
    explanation: 'Yield expresses income generated relative to the price paid — for example, dividend yield.',
  },
  {
    question: "What is an 'index'?",
    options: [
      'A single stock traded on an exchange',
      'A statistical measure tracking the performance of a group of assets',
      'A type of brokerage account',
      'A government tax form',
    ],
    correctIndex: 1,
    explanation: "Indexes like the S&P 500 track a basket of securities to represent a market or sector's performance.",
  },
  {
    question: "What is a company's 'earnings report' primarily used to communicate?",
    options: [
      'Its stock ticker symbol',
      'Its financial performance over a recent period, like revenue and profit',
      'Its CEO\'s salary only',
      'Its stock split schedule',
    ],
    correctIndex: 1,
    explanation: 'Earnings reports summarize how a company performed financially over the quarter or year.',
  },
  {
    question: "What is a 'dividend yield'?",
    options: [
      'The total dollar amount of dividends ever paid',
      "A stock's annual dividend divided by its current price",
      'The tax rate on dividends',
      'The number of shareholders receiving dividends',
    ],
    correctIndex: 1,
    explanation: 'Dividend yield expresses the dividend as a percentage of the current share price.',
  },
  {
    question: "What is 'asset allocation'?",
    options: [
      'Picking a single best stock',
      'How you divide your money across different investment categories, like stocks and bonds',
      'The process of selling all your holdings',
      'A type of brokerage fee',
    ],
    correctIndex: 1,
    explanation: 'Asset allocation is the mix of asset types (stocks, bonds, cash, etc.) that makes up a portfolio.',
  },
];
